#!/usr/bin/env bash
#
set -euo pipefail
shopt -s nullglob # have nothing rather than glob string on no match globs
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
MYPNAME=`basename ${0}`
# 
##
##
## This script Sets up a rendering stages for a single article.  It
## renders and saves the .pdf and repeats for each article like it in
## the same directory.
##
#
BASHDIR="${HOME}/.rinohbox/bashsources"

source  ${BASHDIR}/colorsource

# Make sure we get the argument we derive it all from
TESTARTICLE=${1:-}
if [[ -z "${TESTARTICLE}" ]]; then
    pnameit $(warn "Usage: ${MYPNAME} pathto-article-en.rst") 
    exit 1
fi

TESTARTICLENAME=$(basename ${TESTARTICLE})
TESTARTICLENAMENOEXT=${TESTARTICLENAME%.rst}
if [[ "${TESTARTICLENAME}" == "${TESTARTICLENAMENOEXT}" ]] ; then
    pnameit $(fatal "Abort : no trailing '-en.rst', '-fr.rst', or '-es.rst': ${TESTARTICLENAME}")
    exit 1
fi
# Extract the language code from the name
TESTLANG="${TESTARTICLENAMENOEXT##*-}"  # en,fr or es
if contains ${TESTLANG} "en" "fr" "es" ; then
    true # equivalent to pass
else
    pnameit $(fatal "Abort : no trailing '-en.rst', '-fr.rst', or '-es.rst': ${TESTARTICLENAME}")
    exit 1
fi    

# Need to make test article into a full path name
# derive everything else form that full path name
# all our directories are dricven by where testarticle is

SOURCEDIR=$(dirname ${TESTARTICLE})
# Normalize it to full path
pushd ${SOURCEDIR} >/dev/null
SOURCEDIR=`pwd -P`
popd >/dev/null

SOURCEDIRNAME=$(basename ${SOURCEDIR}) 
SOURCEBASE=$(dirname ${SOURCEDIR})
SOURCEMEDIA="${SOURCEBASE}/${SOURCEDIRNAME}-media"
SOURCEPDFS="${SOURCEBASE}/${SOURCEDIRNAME}-pdfs"
#
pnameit $(info "#####################################################################")
pnameit $(info "${MYPNAME}") ----  $(date "--rfc-3339=seconds")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "This script Sets up a rendering stage for a single article.")
pnameit $(info "It renders and saves the output.pdf and repeats for each other")
pnameit $(info "article like it in the same directory.")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "Article Argument=${TESTARTICLE}")
pnameit $(info "Same Directory=${SOURCEDIR}")
pnameit $(info "Media directory=${SOURCEMEDIA}")
pnameit $(info "Pdfs directory=${SOURCEPDFS}")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "1- Create and initialize a staging directory")
pnameit $(code "newstage" )
stagingdir=$(newstage 2> "${SOURCEPDFS}/newstage.errlog")
pnameit $(info "Result:") $(emph "${stagingdir}" )
OUTPDF="${stagingdir}/output/output.pdf"
do_eacharticle () {
    # - set stage
    # - render
    # - save result
    # - clear stage
    local currentpath
    # echo -e "" > "${SOURCEPDFS}/setstage.errlog"
    # echo -e "" > "${SOURCEPDFS}/sphinx-build.errlog"
    while [[ $# -gt 0 ]]; do
	myname="${1##*/}"
	mynamenoext=${myname%.rst}
	mypdfname="${mynamenoext}.pdf"
	pnameit $(code setstage -s "${stagingdir}" "-l" "${TESTLANG}" "-m" "${SOURCEMEDIA}" "${1}")
	setresult=$(setstage "-s" "${stagingdir}" "-l" "${TESTLANG}" "-m" "${SOURCEMEDIA}" "${1}" 2>> "${SOURCEPDFS}/setstage.errlog")
	pnameit $(code "sphinx-build" "-b" "rinoh" "${stagingdir}/source" "${stagingdir}/output")
	renderresult=$(sphinx-build -b rinoh "${stagingdir}/source" "${stagingdir}/output"  2>> "${SOURCEPDFS}/sphinx-build.errlog")
	pnameit $(code "mv"  "${OUTPDF}" "${SOURCEPDFS}/${mypdfname}")
	ignoreme=$(/usr/bin/mv  "${OUTPDF}" "${SOURCEPDFS}/${mypdfname}" )
	clearresult=$(clearstage "${stagingdir}")
	pnameit $(info "cleared ${clearresult}" )
	shift
    done
}

do_eacharticle ${SOURCEDIR}/*${TESTARTICLENAME: -7} 




