#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
MYPNAME=`basename ${0}`

## This script Sets up a rendering stage for all articles in a
## directory as a single pdf.  It can be done with or without a
## frontpage.
##
## To accomplish this our script nearly identical to a single article
## one.  We take a single article as argument and use that to
## indentify the directory it is in.
##
## Then our script just needs to invokw setstage from that directory
## and upply no article argument.
##
## Other than that we only need to adjust the naming of output .pdf.
#
BASHDIR="${HOME}/.rinohbox/bashsources"

source  ${BASHDIR}/colorsource

#
# Make sure we get the argument that we derive it all from
TESTARTICLE=${1:-}
if [[ -z "${TESTARTICLE}" ]]; then
    pnameit $(warn "Usage: ${MYPNAME} <pathto-article-en.rst>  [<pathto-frontpage-en.rst>]") 
    exit 1
fi
#
#
TESTARTICLENAME=$(basename ${TESTARTICLE})
TESTARTICLENAMENOEXT=${TESTARTICLENAME%.rst}
if [[ "${TESTARTICLENAME}" == "${TESTARTICLENAMENOEXT}" ]] ; then
    pnameit $(warn "Abort : no trailing '-en.rst', '-fr.rst', or '-es.rst': ${TESTARTICLENAME}")
    exit 1
fi
# Extract the language code from the name
TESTLANG="${TESTARTICLENAMENOEXT##*-}"  # en,fr or es
if contains ${TESTLANG} "en" "fr" "es" ; then
    true # equivalent to pass
else
    pnameit $(warn "Abort : no trailing '-en.rst', '-fr.rst', or '-es.rst': ${TESTARTICLENAME}")
    exit 1
fi

# ARTICLESUFFIX="${TESTARTICLE: -7}"  how you get the last 7 characters of a file path

# Need to make test article into a full path name
# derive everything else form that full path name
# all our directories are dricven by where testarticle is
SOURCEDIR=$(dirname ${TESTARTICLE})
# Normalize it to full path
pushd ${SOURCEDIR} >/dev/null
SOURCEDIR=`pwd -P`
popd >/dev/null

SOURCEDIRNAME=$(basename ${SOURCEDIR}) 
SOURCEBASE=$(dirname ${SOURCEDIR})
SOURCEMEDIA="${SOURCEBASE}/${SOURCEDIRNAME}-media"
SOURCEPDFS="${SOURCEBASE}/${SOURCEDIRNAME}-pdfs"

###
### We no longer take frontpage as an argument.
### We use a namning convention.
### Frontpages are named: <SOURCEDIRNAME>frontpage-<TESTLANG>.rst"
### They must be stored in the directory: <SOURCEBASE>/frontpages/
### So if one exists and is readable we use it otherwise we use none.
###
FRONTPAGENAME="${SOURCEDIRNAME}frontpage-${TESTLANG}.rst"
FRONTPAGEFULLNAME="${SOURCEBASE}/frontpages/${FRONTPAGENAME}"
if [[ -r "${FRONTPAGEFULLNAME}" ]]; then
    pnameit $(info "Rendering with front page: ${FRONTPAGENAME}")
else
    pnameit $(info "Rendering with no front page.")
fi

# pushd ${BENCHDIR} >/dev/null
pnameit $(info "#####################################################################")
pnameit $(info "${MYPNAME}") ----  $(date "--rfc-3339=seconds")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "This script Sets up a rendering stage for one single article file.")
pnameit $(info "Then renders it.")
pnameit $(info "Then saves the pdf file in")  $(emph "${SOURCEPDFS}")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "TESTARTICLE=${TESTARTICLE}")
pnameit $(info "TESTARTICLANAMENOEXT=${TESTARTICLENAMENOEXT}")
pnameit $(info "SOURCEDIR=${SOURCEDIR}")
pnameit $(info "SOURCEMEDIA=${SOURCEMEDIA}")
pnameit $(info "SOURCEPDFS=${SOURCEPDFS}")
pnameit $(info "SOURCEDIR=${SOURCEDIR}")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "1- Create and initialize a staging directory")
pnameit $(code "newstage" )
stagingdir=$(newstage 2> "${SOURCEPDFS}/newstage.errlog")
pnameit $(info "Result:") $(emph "${stagingdir}" )
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "2- Set up the stage with article information")

pushd ${SOURCEDIR} >/dev/null

if [[ -r "${FRONTPAGEFULLNAME}" ]]; then
    pnameit $(info "Using front page: ${FRONTPAGENAME}")
    pnameit $(code setstage -s "${stagingdir}" "-l" "${TESTLANG}" "-m" "${SOURCEMEDIA}"  "-f" "${FRONTPAGEFULLNAME}")
    setresult=$(setstage "-s" "${stagingdir}" "-l" "${TESTLANG}" "-m" "${SOURCEMEDIA}" "-f" "${FRONTPAGEFULLNAME}" 2> "${SOURCEPDFS}/setstage.errlog")
else
    pnameit $(info "Using no front page.")
    pnameit $(code setstage -s "${stagingdir}" "-l" "${TESTLANG}" "-m" "${SOURCEMEDIA}")
    setresult=$(setstage "-s" "${stagingdir}" "-l" "${TESTLANG}" "-m" "${SOURCEMEDIA}" 2> "${SOURCEPDFS}/setstage.errlog")    
fi
 
popd >/dev/null
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "3- Render")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(code "sphinx-build" "-b" "rinoh" "${stagingdir}/source" "${stagingdir}/output")
renderresult=$(sphinx-build -b rinoh "${stagingdir}/source" "${stagingdir}/output"  2> "${SOURCEPDFS}/sphinx-build.errlog")
pnameit $(info "4- Preserve the result")
pnameit $(code ln -f -t "${SOURCEPDFS}" "${stagingdir}"'/output/*' )
ingorethis=$(ln -f -t "${SOURCEPDFS}" ${stagingdir}/output/*)
pnameit $(code ln -f "${SOURCEPDFS}/output.pdf" "${SOURCEPDFS}/${TESTARTICLENAMENOEXT}.pdf" )
pnameit $(code  "/usr/bin/mv" "${SOURCEPDFS}/output.pdf" "${SOURCEPDFS}/${TESTARTICLENAMENOEXT}.pdf")
/usr/bin/mv "${SOURCEPDFS}/output.pdf" "${SOURCEPDFS}/${SOURCEDIRNAME}-${TESTLANG}.pdf"	  
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "5- Discard the staging area")
pnameit $(code "rmtage \"${stagingdir}\"")
rmresult=$(rmstage "${stagingdir}" 2> "${SOURCEPDFS}/rmstage.errlog")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "To view use this:") $(emph "xdg-open" "${SOURCEPDFS}/${SOURCEDIRNAME}-${TESTLANG}.pdf")
pnameit 
