#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
#
MYPNAME=$(basename ${0})
# Configure these
BENCHDIR="${HOME}/.rinohbox/benchrst"
REPOFRONTPAGE="${HOME}/repos/rinohbox/test/pdffrontpage-en.rst"
BENCHBASE=$(dirname "${BENCHDIR}")
BASHDIR="${BENCHBASE}/bashsources"
BENCHDIRNAME=$(basename ${BENCHDIR})

# Derive these
BENCHDIRMEDIA="${BENCHDIR}-media"
BENCHDIRPDFS="${BENCHDIR}-pdfs"
REPOARTICLESDIR=$(dirname ${REPOFRONTPAGE})
REPOMEDIADIR="${REPOARTICLESDIR}-media"
FRONTPAGENAME=$(basename "${REPOFRONTPAGE}")
BENCHFRONTPAGE="${BENCHDIR}/${FRONTPAGENAME}"
pushd ${BENCHDIR} >/dev/null

## the article the bench test will render

TESTARTICLE="${BENCHDIR}/sampl-calp003-en.rst"

ERRLOGS=("${BENCHDIRPDFS}/newstage.errlog" "${BENCHDIRPDFS}/setstage.errlog" "${BENCHDIRPDFS}/rmstage.errlog"  )

source  ${BASHDIR}/colorsource

basenms () {
    for apth in "$@"  ; do
	echo -e "${apth##*/}"
    done
}

mapfile -t articlenames < <(basenms ${BENCHDIR}/*-en.rst)

for xarticlename in ${articlenames[@]}; do
    pnameit $(info "----" ${xarticlename})
done

pnameit $(info "#####################################################################")
pnameit $(info "Bench Test") $(date "--rfc-3339=seconds")
pnameit $(info "---------------------------------------------------------------------")

pnameit $(info "using current directory:") $(emph "${BENCHDIR}" )
pnameit $(info "using frontpage:" ) $(code "${BENCHFRONTPAGE}")
pnameit $(info "using articles:" ) $(code "${TESTARTICLE}")
pnameit $(info "using media:" ) $(code "${BENCHDIRMEDIA}")
pnameit $(info "using target:" ) $(code "${BENCHDIRPDFS}")
pnameit $(info "---------------------------------------------------------------------")
#
# make a staging directory
pnameit $(code "newstage")
stagedir=$(newstage 2> "${BENCHDIRPDFS}/newstage.errlog")
pnameit $(code "setstage" "-l" "en" "-s" "${stagedir}" "-f" "FRONTPAGE" "-m" "MEDIA" "-t" "TARGET" "ARTICLE")
setstageresult=$(setstage "-l" "en" "-s" "${stagedir}" "-f" "${BENCHFRONTPAGE}" "-m" "${BENCHDIRMEDIA}" "-t" "${BENCHDIRPDFS}" 2> "${BENCHDIRPDFS}/setstage.errlog")
pnameit $(info "---------------------------------------------------------------------")
if [[ "${setstageresult}" == "${stagedir}" ]] ; then
    pnameit $(info "setstage: confirm result matches  --stagingpath argument")
else
    pnameit $(fatal "setstage: FAILED to confirm result matches  --stagingpath argument")
fi
# do the render
sphinx-build -b rinoh "${stagedir}"/source  "${stagedir}"/output
# grab result 
/usr/bin/ln --force "${stagedir}/output/output.pdf" "${BENCHDIRPDFS}/${BENCHDIRNAME}.pdf"
pnameit $(info "Result: ${BENCHDIRPDFS}/${BENCHDIRNAME}.pdf")


#pnameit $(warn "sphinx-build -b rinoh" "${stagedir}"/source  "${stagedir}"/output)
#pnameit $(warn "/usr/bin/ln --force" "${stagedir}/output/output.pdf" "${BENCHDIRPDFS}/${BENCHDIRNAME}.pdf")

#pnameit $(code "rmstage" "${stagedir}")
#rmresult=$(rmstage "${stagedir}" 2> "${BENCHDIRPDFS}/rmstage.errlog")
#if [[ "${rmresult}" == "${stagedir}" ]] ; then
#    pnameit $(info "rmstage: confirm result matches  argument")
#else
#    pnameit $(fatal "rmstage: FAIL to confirm result matches argument")
#fi
pnameit $(info "${stagedir} has been successfully removed")
pnameit $(info "stderr logs:")
setpindent "    "
for alog in ${ERRLOGS[@]}; do
    pnameit "${alog}"
done
resetpindent
