#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
MYPNAME=`basename ${0}`

# 
##
## This script Sets up a rendering stage for all the articles
## in the same directory as the given article.
## It does this by changing to the correct directory and letting
## the setstage figure out the articles to use.
##
#
BASHDIR="${HOME}/.rinohbox/bashsources"

source  ${BASHDIR}/colorsource
#
# Deliberately give arg1 a default value that will fail
# To force the user to offer the correct one.
#
TESTARTICLE=${1:-/home/ubuntu/.rinohbox/benchrst/default-that-wont-work-xx.rst}
TESTARTICLENAME=$(basename ${TESTARTICLE})
TESTARTICLENAMENOEXT=${TESTARTICLENAME%.rst}
if [[ "${TESTARTICLENAME}" == "${TESTARTICLENAMENOEXT}" ]] ; then
    pnameit $(fatal "Abort : no trailing '-en.rst', '-fr.rst', or '-es.rst': ${TESTARTICLENAME}")
    exit 1
fi
# Extract the language code from the name
TESTLANG="${TESTARTICLENAMENOEXT##*-}"  # en,fr or es
if contains ${TESTLANG} "en" "fr" "es" ; then
    true # equivalent to pass
else
    pnameit $(fatal "Abort : no trailing '-en.rst', '-fr.rst', or '-es.rst': ${TESTARTICLENAME}")
    exit 1
fi

#
# Need to make test article into a full path name
# derive everything else form that full path name
# all our directories are dricven by where testarticle is
#

SOURCEDIR=$(dirname ${TESTARTICLE})
# Normalize it to full path
pushd ${SOURCEDIR} >/dev/null
SOURCEDIR=`pwd -P`
popd >/dev/null

SOURCEDIRNAME=$(basename ${SOURCEDIR}) 
SOURCEBASE=$(dirname ${SOURCEDIR})
SOURCEMEDIA="${SOURCEBASE}/${SOURCEDIRNAME}-media"
SOURCEPDFS="${SOURCEBASE}/${SOURCEDIRNAME}-pdfs"
SOURCEFRONTPAGE="${SOURCEDIR}/pdffrontpage-en.rst"
pnameit $(info "#####################################################################")
pnameit $(info "${MYPNAME}") ----  $(date "--rfc-3339=seconds")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "This script Sets up a rendering stage for all articles in a directory.")
pnameit $(info "Then renders a single .pdf file containing them all.")
pnameit $(info "Then saves the pdf file in")  $(emph "${SOURCEPDFS}")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "TESTARTICLE=${TESTARTICLE}")
pnameit $(info "TESTARTICLANAMENOEXT=${TESTARTICLENAMENOEXT}")
pnameit $(info "SOURCEDIR=${SOURCEDIR}")
pnameit $(info "SOURCEMEDIA=${SOURCEMEDIA}")
pnameit $(info "SOURCEPDFS=${SOURCEPDFS}")
pnameit $(info "SOURCEFRONTPAGE=${SOURCEFRONTPAGE}")
pnameit $(info "SOURCEDIR=${SOURCEDIR}")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "1- Create and initialize a staging directory")
pnameit $(code "newstage" )
stagingdir=$(newstage)
pnameit $(info "Result:") $(emph "${stagingdir}" )
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "2- Set the article into the stage")
pnameit $(code setstage -s "${stagingdir}" "-l" "${TESTLANG}" "-m" "${SOURCEMEDIA}" -t "${SOURCEPDFS}" "${TESTARTICLE}")

# setresult=$(setstage "-l" "${TESTLANG}" "-s" "${stagingdir}" "-m" "${SOURCEMEDIA}" "-t" "${SOURCEPDFS}" 2> "${SOURCEPDFS}/setstage.errlog")
pushd ${SOURCEDIR} >/dev/null
setresult=$(setstage -s "${stagingdir}" -l "${TESTLANG}" -m "${SOURCEMEDIA}" -t "${SOURCEPDFS}")
popd >/dev/null
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "3- Render")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(code "sphinx-build" "-b" "rinoh" "${stagingdir}/source" "${stagingdir}/output")
renderresult=$(sphinx-build -b rinoh "${stagingdir}/source" "${stagingdir}/output"  2> "${SOURCEPDFS}/sphinx-build.errlog")
pnameit $(info "4- Preserve the result")
pnameit $(code ln -f -t "${SOURCEPDFS}" "${stagingdir}"'/output/*' )
ingorethis=$(ln -f -t "${SOURCEPDFS}" ${stagingdir}/output/*)
pnameit $(code ln -f "${SOURCEPDFS}/output.pdf" "${SOURCEPDFS}/${TESTARTICLENAMENOEXT}.pdf" )
pnameit $(code  "/usr/bin/mv" "${SOURCEPDFS}/output.pdf" "${SOURCEPDFS}/${SOURCEDIRNAME}.pdf")
/usr/bin/mv "${SOURCEPDFS}/output.pdf" "${SOURCEPDFS}/${SOURCEDIRNAME}.pdf"	  
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "5- Discard the staging area")
pnameit $(code "rmtage \"${stagingdir}\"")
rmresult=$(rmstage "${stagingdir}")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "To view use this:") $(emph xdg-open "${SOURCEPDFS}/${SOURCEDIRNAME}.pdf")
pnameit 
