#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
#
#
MYPNAME=$(basename ${0})
source  /home/ubuntu/repos/rinohtools/colorsource

showcolortest
echo 
showmessages
echo


