#!/usr/bin/env bash
# colordecorations

##!/usr/bin/env bash
##
#set -euo pipefail
##
## bash trick to obtain a clean absolute path to this script.
##
#pushd `dirname $0` >/dev/null
#SCRIPTPATH=`pwd -P`
#popd >/dev/null
##
##
#MYPNAME=$(basename ${0})

# This file must be sourced in bash scripts that set the MYPNAME global variable
# similar to the above comments.  source this file AFTER MPNAME is set
# See colortest as an example.

#_X_INDENT

#
# Other handy functions
#    Returns 0 if the first argument is within the others
# Use like this:
#
##--list=("apple" "banana" "cherry")
##--
##--if contains "banana" "${list[@]}"; string then
##--    echo "match found"
##--else
##--    echo "no match"
##--fi
##--
contains() {
    local target="$1"
    shift
    local item
    for item in "$@"; do
        [[ "$item" == "$target" ]] && return 0
    done
    return 1
}

# color stuff
#

strdecor () {
    
    case ${1} in
	
	black)
	    echo '\033[30m'
	    ;;
	    
        red)
	    echo '\033[31m'
	    ;;

        yellow)
	    echo '\033[33m'
	    ;;
		      
        white)
	    echo '\033[37m'
	    ;;

        reset)
	    echo '\033[0m'
	    ;;

        bold)
	    echo '\033[1m'
	    ;;

        dim)
	    echo '\033[2m'
	    ;;

        underline)
	    echo '\033[4m'
	    ;;

        green)
	    echo '\033[32m'
	    ;;

        blue)
	    echo '\033[34m'
	    ;;

        magenta)
	    echo '\033[35m'
	    ;;

        cyan)
	    echo '\033[36m'
	    ;;

	*)
	    echo "${1}"
    esac
}

fatal () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local mycolor=$(strdecor "red")
    echo -e "${bold}${mycolor}${@}${reset}"
}

warn () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local mycolor=$(strdecor "yellow")
    echo -e "${bold}${mycolor}${@}${reset}"
}

info () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local mycolor=$(strdecor "cyan")
    echo -e "${bold}${mycolor}${@}${reset}"
}
emph () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local mycolor=$(strdecor "white")
    echo -e "${bold}${mycolor}${@}${reset}"
}

colour () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local mycolor=$(strdecor "$1")
    echo -e "${bold}${mycolor}${@:2}${reset}"    
}

clr () {
    local mycolor=$(strdecor "$1")
    echo -e "${mycolor}${@:2}"    
}

clrdim () {
    local mycolor=$(strdecor "dim")
    echo -e "${mycolor}"    
}

clrul () {
    local mycolor=$(strdecor "underline")
    echo -e "${mycolor}"    
}

clrbold () {
    local mycolor=$(strdecor "bold")
    echo -e "${mycolor}"    
}

clrreset () {
    local reset=$(strdecor "reset")
    echo -e "${reset}"    
}

code () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local mycolor=$(strdecor "magenta")
    echo -e "${bold}${mycolor}${@}${reset}"    
}

_X_PNAME_INDENT=""
pnameit () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local pgmnam=$(colour "green" "${MYPNAME}")
    echo -e "${pgmnam}:${_X_PNAME_INDENT} ${@}"
}
 
countedindent () {
    local astr=""
    for i in $(seq 1 ${#1}); do
	astr="${astr} "
    done
    echo -e "${astr}"
}


_X_INDENT=$(countedindent "${MYPNAME}: ")
dashedindent () {
    local astr=""
    for i in $(seq 1 ${#_X_INDENT}); do
	astr="${astr}-"
    done
    echo -e "${astr}"
}
_X_DASH_INDENT=$(dashedindent)
 

setindent () {
    _X_INDENT=$(countedindent "${1}" )
    _X_DASH_INDENT=$(dashedindent)
}

resetindent () {
    _X_INDENT=$(countedindent "${MYPNAME}: " )
    _X_DASH_INDENT=$(dashedindent)
}

setpindent () {
    _X_PNAME_INDENT=$(countedindent "${1}" )
}

resetpindent () {
    _X_PNAME_INDENT=""
}

indentit () {
    echo -e "${_X_INDENT}${_X_PNAME_INDENT}${@}"
}

dashit () {
    local bold=$(strdecor "bold")
    local reset=$(strdecor "reset")
    local mycolor=$(strdecor "$1")
    local myprefix="${_X_DASH_INDENT}" 
    echo -e "${bold}${mycolor}${myprefix}${reset}${_X_PNAME_INDENT}${@:2}"
}


printit () {
    echo -e "${_X_PNAME_INDENT}${@}"
}




showmessages () {
    pnameit $(fatal "this" "is a" "fatal")
    pnameit $(warn "this" "is a" "warn")
    pnameit $(info "this" "is an" "info")
    pnameit $(emph "this" "is an" "emph")
    pnameit $(code "this" "is a" "code")
}

showcolortest () {
    pnameit "          " $(clr "oops" ) $(clr "green" "green") $(clr "yellow" "yellow") $(clr "white" "white") $(clr "red" "red") $(clr "blue" "blue") $(clr "black" "black") $(clr "magenta" "magenta") $(clr "cyan" "cyan")$(clrreset)
    pnameit "ul:       " $(clrul)$(clr "oops" ) $(clr "green" "green") $(clr "yellow" "yellow") $(clr "white" "white") $(clr "red" "red") $(clr "blue" "blue") $(clr "black" "black") $(clr "magenta" "magenta") $(clr "cyan" "cyan")$(clrreset)
    pnameit "dim:      " $(clrdim)$(clr "oops" ) $(clr "green" "green") $(clr "yellow" "yellow") $(clr "white" "white") $(clr "red" "red") $(clr "blue" "blue") $(clr "black" "black") $(clr "magenta" "magenta") $(clr "cyan" "cyan")$(clrreset)
    pnameit "dim+ul    " $(clrdim)$(clrul)$(clr "oops" ) $(clr "green" "green") $(clr "yellow" "yellow") $(clr "white" "white") $(clr "red" "red") $(clr "blue" "blue") $(clr "black" "black") $(clr "magenta" "magenta") $(clr "cyan" "cyan")$(clrreset)
    pnameit "bold      " $(clrbold)$(clr "oops" ) $(clr "green" "green") $(clr "yellow" "yellow") $(clr "white" "white") $(clr "red" "red") $(clr "blue" "blue") $(clr "black" "black") $(clr "magenta" "magenta") $(clr "cyan" "cyan")$(clrreset)
    pnameit "bold+ul   " $(clrbold)$(clrul)$(clr "oops" ) $(clr "green" "green") $(clr "yellow" "yellow") $(clr "white" "white") $(clr "red" "red") $(clr "blue" "blue") $(clr "black" "black") $(clr "magenta" "magenta") $(clr "cyan" "cyan")$(clrreset)    

}
