#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
SCRIPPATH=$(pwd)
#
#
MYPNAME=$(basename ${0})

# Configure these
BENCHDIR="${HOME}/.rinohbox/benchrst"
REPOPREAMBLE="${HOME}/repos/rinohbox/test/pdfpreamble.rst"
BENCHBASE=$(dirname "${BENCHDIR}")
BASHDIR="${BENCHBASE}/bashsources"


# Derive these
BENCHDIRMEDIA="${BENCHDIR}-media"
BENCHDIRPDFS="${BENCHDIR}-pdfs"
REPOARTICLESDIR=$(dirname ${REPOPREAMBLE})
REPOMEDIADIR="${REPOARTICLESDIR}-media"
PREAMBLENAME=$(basename "${REPOPREAMBLE}")
BENCHPREAMBLE="${BENCHDIR}/${PREAMBLENAME}"
#
#
# source  "${BASHDIR}/colorsource"
# in this script the above source one does not exist yet
source  "${SCRIPTPATH}/colorsource"

bashscripts () {
    [[ -r "${SCRIPPATH}/colorsource" ]] && echo -e "${SCRIPPATH}/colorsource"
    [[ -r "${SCRIPPATH}/colorit" ]] && echo -e "${SCRIPPATH}/colorit"
    [[ -r "${SCRIPPATH}/colortest" ]] && echo -e "${SCRIPPATH}/colortest"
    [[ -r "${SCRIPPATH}/single2pdf" ]] && echo -e "${SCRIPPATH}/single2pdf"
    [[ -r "${SCRIPPATH}/allapart2pdf" ]] && echo -e "${SCRIPPATH}/allapart2pdf"
    [[ -r "${SCRIPPATH}/alltogether2pdf" ]] && echo -e "${SCRIPPATH}/alltogether2pdf"
}

 


mapfile -t bashinstalls < <(bashscripts)

basenms () {
    for apth in "$@"  ; do
	echo -e "${apth##*/}"
    done
}

mapfile -t articlenames < <(basenms ${REPOARTICLESDIR}/*.rst)
mapfile -t mediafiles < <(basenms ${REPOMEDIADIR}/*)

mapfile -t rinohpath <<'EOF'

# Added this for rinobox to .profile
# It adds our scripts to the search path
if [ -d "${HOME}/.rinohbox/bashsources" ] ; then
    PATH="${HOME}/.rinohbox/bashsources:${PATH}"
fi

EOF


# make each subdirectory unless it exists
mkdir -p "${BASHDIR}"
mkdir -p "${BENCHDIR}" 
mkdir -p "${BENCHDIRMEDIA}"
mkdir -p "${BENCHDIRPDFS}" 

pnameit $(info "ABOUT ${MYPNAME}")
pnameit $(info "------------------")
pnameit $(info "This installs collateral tools useful for")
pnameit $(info "testing and working with the rinohbox package.")
pnameit $(info "The rinohbox package itself is installed using ")
pnameit $(info "pip and/or flit into our current virtual environment.")
pnameit $(info "")
pnameit $(info "We install: CONVENIENCE SCRIPTS and BENCH TEST SETUP")
pnameit $(info "")
 
pnameit $(info "CONVENIENCE SCRIPTS")
setpindent "    "
pnameit $(info "Bash Scripts: (in" ) $(emph "${BASHDIR}") $(info ")") 
setpindent "        "
# copy scripts 
for aname in "${bashinstalls[@]}"; do
    briefname=$(basename "${aname}")
    if [[ "${briefname}" == "colorsource" ]]; then
	pnameit "${briefname}"
    else
	pnameit $(colour "green" "${briefname}")
    fi	
    $(cp "${SCRIPTPATH}/${briefname}" "${BASHDIR}/${briefname}")
done 
setpindent "    "
pnameit $(info "Recommendation: code snippet to  \${HOME}/.profile:") 
setpindent "        "
pnameit $(info 'Adding the code snippet at the bottom to .profile')
pnameit $(info 'and our scripts will be in the search path.')
setpindent "    "
pnameit $(info "BENCH TEST SETUP")
setpindent "    "
pnameit $(info "Bench Directory:") $(emph "${BENCHDIR}")
pnameit $(info "Results:") "       " $(emph "${BENCHDIRPDFS}")
pnameit $(info "Bench Test Data")
setpindent "        "
pnameit $(info "Articles: (in" ) $(emph "${BENCHDIR}") $(info ")") 
setpindent "            "
# copy articles REPOARTICLESDIR to BENCHDIR
for aname in "${articlenames[@]}"; do
    briefname=$(basename "${aname}")
    pnameit "${aname}"
    $(cp "${REPOARTICLESDIR}/${briefname}" "${BENCHDIR}/${briefname}")
done

setpindent "        "
pnameit  $(info "Media: (in") $(emph "${BENCHDIRMEDIA}") $(info ")") 
setpindent "            "
# copy media REPOMEDIADIR to BENCHDIRMEDIA
for aname in "${mediafiles[@]}"; do
    briefname=$(basename "${aname}")
    pnameit $(colour "magenta" "${briefname}")
    $(cp "${REPOMEDIADIR}/${briefname}" "${BENCHDIRMEDIA}/${briefname}")
done
resetpindent
resetindent
for item in "${rinohpath[@]}" ; do
    printit $(colour "magenta" "${item}")    
done


