#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
#
MYPNAME=$(basename ${0})
MYSOURCESDIR="${HOME}/.rinohbox/bashsources"
MYTESTBED=${HOME}/.rinohbox/benchrst
DLFTRSTIN="${MYTESTBED}"
DFLTPDFOUT="${DLFTRSTIN}-pdfs"
MYPREAMBLE="${DLFTRSTIN}/pdfpreamble.rst"

pushd ${MYTESTBED} >/dev/null
source  ${MYSOURCESDIR}/colorsource
pnameit $(warn 'This script set current directory to') $(emph "${MYTESTBED}" )
pnameit $(warn 'This script relies on ')$(emph ${MYSOURCESDIR}/colorsource )
pnameit $(info "using preamble:" ) $(code "${MYPREAMBLE}")
pnameit $(info "using article:" ) $(code "${DLFTRSTIN}/sampl-calp001-en.rst")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "This scrip wants either one or no arguments.")
pnameit $(info "When it is none.  I creates a new  rinoh sandbox.")
pnameit $(info "---------------------------------------------------------------------")
mycount="${#@}"
pnameit $(warn "number of arguments" "${mycount}")
if [[ $mycount > 0 ]] ; then
    aboxdir="${1}"
    pnameit $(info "request to remove") $(emph  "${aboxdir}")
    boxdir=$(rmrinoh "${aboxdir}")
    pnameit $(info "removed") $(emph  "${boxdir}")
    # 
else
    pnameit $(info "this is a create request")
    boxdir=$(newrinoh)
    pnameit $(info  "boxdir:") $(emph  "${boxdir}") 
fi
