#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
#
MYPNAME=$(basename ${0})
# Configure these
BENCHDIR="${HOME}/.rinohbox/benchrst"
REPOPREAMBLE="${HOME}/repos/rinohbox/test/pdfpreamble.rst"
BENCHBASE=$(dirname "${BENCHDIR}")
BASHDIR="${BENCHBASE}/bashsources"

# Derive these
BENCHDIRMEDIA="${BENCHDIR}-media"
BENCHDIRPDFS="${BENCHDIR}-pdfs"
REPOARTICLESDIR=$(dirname ${REPOPREAMBLE})
REPOMEDIADIR="${REPOARTICLESDIR}-media"
PREAMBLENAME=$(basename "${REPOPREAMBLE}")
BENCHPREAMBLE="${BENCHDIR}/${PREAMBLENAME}"
pushd ${BENCHDIR} >/dev/null
source  ${BASHDIR}/colorsource
pnameit $(warn 'This script set current directory to') $(emph "${BENCHDIR}" )
pnameit $(warn 'It does that so that other sripts we use have convenient defaults.')
pnameit $(warn 'This script relies on ')$(emph ${BASHDIR}/colorsource )
pnameit $(info "using preamble:" ) $(code "${BENCHPREAMBLE}")
pnameit $(info "using article:" ) $(code "${BENCHDIR}/sampl-calp001-en.rst")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "help")
mapfile -t helpresult < <(renderrinoh --help)
pnameit ""
for item in "${helpresult[@]}" ; do
    pnameit "${item}"
done
pnameit $(info "---------------------------------------------------------------------")
#
# make a sandbox
sanbox=$(newrinoh)
#pnameit "preamble: "${BENCHPREAMBLE}"
pnameit "command:" "renderrinoh" "--boxpath" "${sanbox}" "--preamble" "${BENCHPREAMBLE}"
renderresult=$(renderrinoh "--boxpath" "${sanbox}" "--preamble" "${BENCHPREAMBLE}")
pnameit "renderrinoh returned ${renderresult}"
rmresult=$(rmrinoh "${sandbox}")
pnameit "rmrinoh returned ${rmresult}"

