#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
#
MYPNAME=$(basename ${0})
# Configure these
BENCHDIR="${HOME}/.rinohbox/benchrst"
REPOPREAMBLE="${HOME}/repos/rinohbox/test/pdfpreamble.rst"
BENCHBASE=$(dirname "${BENCHDIR}")
BASHDIR="${BENCHBASE}/bashsources"

# Derive these
BENCHDIRMEDIA="${BENCHDIR}-media"
BENCHDIRPDFS="${BENCHDIR}-pdfs"
REPOARTICLESDIR=$(dirname ${REPOPREAMBLE})
REPOMEDIADIR="${REPOARTICLESDIR}-media"
PREAMBLENAME=$(basename "${REPOPREAMBLE}")
BENCHPREAMBLE="${BENCHDIR}/${PREAMBLENAME}"
pushd ${BENCHDIR} >/dev/null

## the article the bench test will render

TESTARTICLE="${BENCHDIR}/sampl-calp003-en.rst"

ERRLOGS=("${BENCHDIRPDFS}/newstage.errlog" "${BENCHDIRPDFS}/setstage.errlog" "${BENCHDIRPDFS}/rmstage.errlog"  )

source  ${BASHDIR}/colorsource

basenms () {
    for apth in "$@"  ; do
	echo -e "${apth##*/}"
    done
}

mapfile -t articlenames < <(basenms ${BENCHDIR}/*-en.rst)

for xarticlename in ${articlenames[@]}; do
    pnameit $(info "----" ${xarticlename})
done

pnameit $(info "#####################################################################")
pnameit $(info "Bench Test") $(date "--rfc-3339=seconds")
pnameit $(info "---------------------------------------------------------------------")

pnameit $(info "using current directory:") $(emph "${BENCHDIR}" )
pnameit $(info "using preamble:" ) $(code "${BENCHPREAMBLE}")
pnameit $(info "using articles:" ) $(code "${TESTARTICLE}")
pnameit $(info "using media:" ) $(code "${BENCHDIRMEDIA}")
pnameit $(info "using target:" ) $(code "${BENCHDIRPDFS}")
pnameit $(info "---------------------------------------------------------------------")
#
# make a staging directory
pnameit $(code "newstage")
stagedir=$(newstage 2> "${BENCHDIRPDFS}/newstage.errlog")
pnameit $(code "setstage" "-l" "en" "-s" "${stagedir}" "-p" "PREAMBLE" "-m" "MEDIA" "-t" "TARGET" "ARTICLE")
setstageresult=$(setstage "-l" "en" "-s" "${stagedir}" "-p" "${BENCHPREAMBLE}" "-m" "${BENCHDIRMEDIA}" "-t" "${BENCHDIRPDFS}" 2> "${BENCHDIRPDFS}/setstage.errlog")
# pnameit $(code "rmstage" "${stagedir}")
# rmresult=$(rmstage "${stagedir}" 2> "${BENCHDIRPDFS}/rmstage.errlog")
pnameit $(info "---------------------------------------------------------------------")
if [[ "${setstageresult}" == "${stagedir}" ]] ; then
    pnameit $(info "setstage: confirm result matches  --stagingpath argument")
else
    pnameit $(fatal "setstage: FAILED to confirm result matches  --stagingpath argument")
fi
#rmresult=$(rmstage "${stagedir}" 2> "${BENCHDIRPDFS}/rmstage.errlog")
#if [[ "${rmresult}" == "${stagedir}" ]] ; then
#    pnameit $(info "rmstage: confirm result matches  argument")
#else
#    pnameit $(fatal "rmstage: FAIL to confirm result matches argument")
#fi
pnameit $(info "${stagedir} has been successfully removed")
pnameit $(info "stderr logs:")
setpindent "    "
for alog in ${ERRLOGS[@]}; do
    pnameit "${alog}"
done
resetpindent
