#!/usr/bin/env bash
#
set -euo pipefail
#
# bash trick to obtain a clean absolute path to this script.
#
pushd `dirname $0` >/dev/null
SCRIPTPATH=`pwd -P`
popd >/dev/null
#
MYPNAME=$(basename ${0})
# Configure these
BENCHDIR="${HOME}/.rinohbox/benchrst"
REPOPREAMBLE="${HOME}/repos/rinohbox/test/pdfpreamble.rst"
BENCHBASE=$(dirname "${BENCHDIR}")
BASHDIR="${BENCHBASE}/bashsources"

# Derive these
BENCHDIRMEDIA="${BENCHDIR}-media"
BENCHDIRPDFS="${BENCHDIR}-pdfs"
REPOARTICLESDIR=$(dirname ${REPOPREAMBLE})
REPOMEDIADIR="${REPOARTICLESDIR}-media"
PREAMBLENAME=$(basename "${REPOPREAMBLE}")
BENCHPREAMBLE="${BENCHDIR}/${PREAMBLENAME}"
pushd ${BENCHDIR} >/dev/null
source  ${BASHDIR}/colorsource
pnameit $(warn 'This script set current directory to') $(emph "${BENCHDIR}" )
pnameit $(warn 'It does that so that other sripts we use have convenient defaults.')
pnameit $(warn 'This script relies on ')$(emph ${BASHDIR}/colorsource )
pnameit $(info "using preamble:" ) $(code "${BENCHPREAMBLE}")
pnameit $(info "using article:" ) $(code "${BENCHDIR}/sampl-calp001-en.rst")
pnameit $(info "---------------------------------------------------------------------")
pnameit $(info "help")
mapfile -t helpresult < <(renderrinoh --help)
pnameit ""
for item in "${helpresult[@]}" ; do
    pnameit "${item}"
done
pnameit $(info "---------------------------------------------------------------------")
#
# make a sandbox
sandbox=$(newrinoh)
#pnameit "preamble: "${BENCHPREAMBLE}"
pnameit "command:" "renderrinoh" "--boxpath" "${sandbox}" "--preamble" "${BENCHPREAMBLE}"
renderresult=$(renderrinoh "--boxpath" "${sandbox}" "--preamble" "${BENCHPREAMBLE}")
pnameit "renderrinoh returned ${renderresult}"
if [[ "${renderresult}" == "${sandbox}" ]] ; then
    pnameit $(info "renderrinoh: Matching result and  --boxpath argument")
else
    pnameit $(fatal "renderrinoh: Mismatching result and  --boxpath argument")
fi
rmresult=$(rmrinoh "${sandbox}")
if [[ "${rmresult}" == "${sandbox}" ]] ; then
    pnameit $(info "rmrinoh: Matching result and  argument")
else
    pnameit $(fatal "rmrinoh: Mismatching result and argument")
fi
pnameit $(info "rhinobox:${sandbox} has been successfully removed")
